CI dotnet 3.1.101 -> 3.1.300

diff --git a/.github/workflows/ci_package.yml b/.github/workflows/ci_package.yml
--- a/.github/workflows/ci_package.yml
+++ b/.github/workflows/ci_package.yml
@@ -1,53 +1,51 @@
 name: Build & Publish NuGet Packages
 
-on: 
+on:
   push:
-    branches-ignore: [ master ]
+    branches-ignore: [master]
 
 env:
   BUILD_CONFIGURATION: Release
   SOURCE_DIRECTORY: ./src
-  
+
 jobs:
-     
   build:
     name: Create CI NuGet Packages
     runs-on: ubuntu-latest
 
     steps:
-    
-    - name: Checkout Code
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-      
-    - name: Checkout Tags
-      run: git fetch -t
+      - name: Checkout Code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
 
-    - name: Validate License Headers
-      run: |
-        LIC_HEADER_COUNT=$(find . -name '*.cs' -exec grep -H -E -o -c "Copyright \(c\) Microsoft Corporation\." {} \; -exec grep -H -E -o -c "Licensed under the MIT License\." {} \;)
-        LIC_HEADER_MISSING="$( echo "$LIC_HEADER_COUNT" | grep ':0$' || : )"
-        #[ ! -z "$LIC_HEADER_MISSING" ] && echo -e "Missing License Header:\n$LIC_HEADER_MISSING" && exit 1
-      working-directory: ${{ env.SOURCE_DIRECTORY }}
-      
-    - name: Setup GitVersion
-      uses: gittools/actions/gitversion/setup@v0.9.2
-      with:
+      - name: Checkout Tags
+        run: git fetch -t
+
+      - name: Validate License Headers
+        run: |
+          LIC_HEADER_COUNT=$(find . -name '*.cs' -exec grep -H -E -o -c "Copyright \(c\) Microsoft Corporation\." {} \; -exec grep -H -E -o -c "Licensed under the MIT License\." {} \;)
+          LIC_HEADER_MISSING="$( echo "$LIC_HEADER_COUNT" | grep ':0$' || : )"
+          #[ ! -z "$LIC_HEADER_MISSING" ] && echo -e "Missing License Header:\n$LIC_HEADER_MISSING" && exit 1
+        working-directory: ${{ env.SOURCE_DIRECTORY }}
+
+      - name: Setup GitVersion
+        uses: gittools/actions/gitversion/setup@v0.9.2
+        with:
           versionSpec: '5.2.4'
 
-    - name: Execute GitVersion
-      id: gitversion
-      uses: gittools/actions/gitversion/execute@v0.9.2
+      - name: Execute GitVersion
+        id: gitversion
+        uses: gittools/actions/gitversion/execute@v0.9.2
 
-    - name: Setup .NET Core
-      uses: actions/setup-dotnet@v1
-      with:
-        dotnet-version: '3.1.101'
+      - name: Setup .NET Core
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: '3.1.300'
 
-    - name: Build & Package for CI
-      run:  dotnet build -c ${{ env.BUILD_CONFIGURATION }} -p:VersionPrefix="${{ steps.gitversion.outputs.majorMinorPatch }}" -p:AssemblyVersion="${{ steps.gitversion.outputs.assemblySemVer }}" -p:FileVersion="${{ steps.gitversion.outputs.assemblySemFileVer }}" -p:IncludeSymbols=true --version-suffix "ci-${{ steps.gitversion.outputs.preReleaseTag }}"
-      working-directory: ${{ env.SOURCE_DIRECTORY }}
+      - name: Build & Package for CI
+        run: dotnet build -c ${{ env.BUILD_CONFIGURATION }} -p:VersionPrefix="${{ steps.gitversion.outputs.majorMinorPatch }}" -p:AssemblyVersion="${{ steps.gitversion.outputs.assemblySemVer }}" -p:FileVersion="${{ steps.gitversion.outputs.assemblySemFileVer }}" -p:IncludeSymbols=true --version-suffix "ci-${{ steps.gitversion.outputs.preReleaseTag }}"
+        working-directory: ${{ env.SOURCE_DIRECTORY }}
 
-    - name: Publish NuGet Packages to MyGet
-      run: dotnet nuget push '**/*.nupkg' --api-key '${{ secrets.MYGET_DEV_TOKEN }}' --source 'https://www.myget.org/F/teamcloud-dev/api/v2/package' --symbol-api-key '${{ secrets.MYGET_DEV_TOKEN }}' --symbol-source 'https://www.myget.org/F/teamcloud-dev/symbols/api/v2/package' --skip-duplicate
+      - name: Publish NuGet Packages to MyGet
+        run: dotnet nuget push '**/*.nupkg' --api-key '${{ secrets.MYGET_DEV_TOKEN }}' --source 'https://www.myget.org/F/teamcloud-dev/api/v2/package' --symbol-api-key '${{ secrets.MYGET_DEV_TOKEN }}' --symbol-source 'https://www.myget.org/F/teamcloud-dev/symbols/api/v2/package' --skip-duplicate
