Update packaging.yml

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -21,6 +21,14 @@ jobs:
     - name: Checkout Tags
       run: git fetch -t
         
+    - name: Validate License Headers
+      run: |
+        MISSING_LIC_HEADER=$(find . -name '*.cs' ! -path '**/obj/*' ! -path '**/bin/*' \
+        -exec grep  -H -E -o -c "Copyright \(c\) Microsoft Corporation\."  {} \; \
+        -exec grep  -H -E -o -c "Licensed under the MIT License\."  {} \; | grep 0)
+        [ ! -z "$MISSING_LIC_HEADER" ] && echo -e "Missing License Header:\n$MISSING_LIC_HEADER" && exit 1
+      working-directory: ${{ env.SOURCE_DIRECTORY }}
+      
     - name: Setup GitVersion
       uses: gittools/actions/gitversion/setup@v0.6.1
       with:
