Update packaging.yml

diff --git a/.github/workflows/packaging.yml b/.github/workflows/packaging.yml
--- a/.github/workflows/packaging.yml
+++ b/.github/workflows/packaging.yml
@@ -25,8 +25,8 @@ jobs:
       run: |
         LIC_HEADER_COUNT=$(find . -name '*.cs' -exec grep -H -E -o -c "Copyright \(c\) Microsoft Corporation\." {} \; -exec grep -H -E -o -c "Licensed under the MIT License\." {} \;)
         echo "$LIC_HEADER_COUNT" | grep ':0$' || :
-        #LIC_HEADER_MISSING=$(echo "$LIC_HEADER_COUNT" | grep ':0$' || echo "")
-        #echo "$LIC_HEADER_MISSING"
+        LIC_HEADER_MISSING="$( echo "$LIC_HEADER_COUNT" | grep ':0$' || : )"
+        echo "$LIC_HEADER_MISSING"
         #[ ! -z "$LIC_HEADER_MISSING" ] && echo -e "Missing License Header:\n$LIC_HEADER_MISSING" && exit 1
       working-directory: ${{ env.SOURCE_DIRECTORY }}
       
